"use client";
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Check,MapPin} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';

export default function Home(){
 const [age,setAge]=useState(''); const [consent,setConsent]=useState(false); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'open_enquiry_form',description:'Открыть форму заявки на занятия. Не отправляет заявку.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Ожидается пустой объект.');document.getElementById('enquiry')?.scrollIntoView({behavior:'instant'});document.getElementById('parent')?.focus();return {form:'enquiry',submitted:false};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setStatus('');if(!age||!consent){setStatus('Выберите возраст ребёнка и подтвердите согласие.');return;}const f=new FormData(e.currentTarget);setBusy(true);try{const r=await fetch('/api/enquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),phone:f.get('phone'),age,comment:f.get('comment'),consent,website:f.get('website')})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Не удалось отправить заявку. Попробуйте ещё раз или позвоните нам.');setDone(true);}catch(e){setStatus(e instanceof Error?e.message:'Не удалось отправить заявку. Попробуйте ещё раз.');}finally{setBusy(false);}}
 return <><header className="header"><a href="#" aria-label="ТЭНЦ — на главную"><img className="logo" src="/logo.svg" alt="Танцевальная студия ТЭНЦ"/></a><nav aria-label="Основная навигация"><a href="#directions">О занятиях</a><a href="#enquiry">Запись</a><a href="#contacts">Контакты</a></nav><a className="header-cta" href="#enquiry">Оставить заявку <ArrowUpRight size={17}/></a></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> ОДИНЦОВО · ДЕТИ 7–9 ЛЕТ</div><h1>Большое искусство<br/>начинается<br/><em>с маленького шага.</em></h1><p className="lead">Балет и современная хореография в «ТЭНЦ».<br className="desktop"/> Пространство, где ребёнок открывает танец.</p><a className="primary" href="#enquiry">Записаться на занятия <ArrowUpRight size={20}/></a><div className="hero-bottom"><span>Классическая основа.</span><span>Свобода движения.</span></div></div><figure className="hero-art"><img src="/ballerina.webp" alt="Балерина в светлом классическом зале — художественный образ"/><figcaption>ТАНЕЦ КАК НАЧАЛО БОЛЬШОЙ ИСТОРИИ</figcaption><span className="vertical-note" aria-hidden="true">BALLET & CONTEMPORARY</span></figure></section>
 <section className="directions section" id="directions"><div className="section-heading"><p className="eyebrow">01 / НАПРАВЛЕНИЯ</p><h2>Техника и чувства.<br/><em>В одном движении.</em></h2><p>Два направления, которые дополняют друг друга: точность классики и выразительность современной хореографии.</p></div><div className="direction-list"><article><span className="number">01</span><div><h3>Балет</h3><p>Знакомство с классической хореографией: положение корпуса, координация, работа рук и ног, чувство музыки.</p><span className="tag">ОСНОВА И ГРАЦИЯ</span></div></article><article><span className="number">02</span><div><h3>Современная хореография</h3><p>Работа с ритмом и пространством, танцевальные сочетания и импровизация. Учимся выражать себя через движение.</p><span className="tag">СВОБОДА И ВЫРАЗИТЕЛЬНОСТЬ</span></div></article></div></section>
 <section className="enquiry-section" id="enquiry"><div className="enquiry-story"><p className="eyebrow">02 / ПЕРВЫЙ ШАГ</p><h2>Пусть знакомство<br/>с танцем будет<br/><em>красивым.</em></h2><p>Оставьте заявку. Администратор свяжется с вами, расскажет о расписании и стоимости и поможет записаться в группу 7–9 лет.</p><div className="pointe-frame"><img src="/pointe.webp" alt="Атласные пуанты с лентами" loading="lazy"/></div></div><div className="form-card">{done?<div className="success" role="status"><span className="success-icon"><Check size={32}/></span><p className="eyebrow">ПЕРВЫЙ ШАГ СДЕЛАН</p><h3>Спасибо за заявку!</h3><p>Заявка передана студии. Администратор свяжется с вами по указанному телефону.</p><a href="tel:+79775553344">+7 977 555-33-44</a></div>:<form onSubmit={submit}><p className="eyebrow">ЗАНЯТИЯ ДЛЯ ДЕТЕЙ 7–9 ЛЕТ</p><h3>Запись в студию</h3><p className="form-intro">Познакомимся и подберём занятия для вашего ребёнка.</p><label htmlFor="parent">Ваше имя <span>*</span></label><input id="parent" name="name" autoComplete="given-name" placeholder="Как к вам обращаться" required maxLength={60}/><div className="form-row"><div><label htmlFor="phone">Телефон <span>*</span></label><input id="phone" name="phone" type="tel" autoComplete="tel" placeholder="+7 (999) 123-45-67" required minLength={10} maxLength={22}/></div><div><label htmlFor="age">Возраст ребёнка <span>*</span></label><Select value={age} onValueChange={setAge} required><SelectTrigger id="age" className="age-select"><SelectValue placeholder="Выберите"/></SelectTrigger><SelectContent>{['7','8','9'].map(n=><SelectItem key={n} value={n}>{n} лет</SelectItem>)}</SelectContent></Select></div></div><label htmlFor="comment">Ваш вопрос <span className="optional">необязательно</span></label><textarea id="comment" name="comment" placeholder="Например, можно ли начать без подготовки?" rows={3} maxLength={250}/><div className="trap" aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off"/></div><div className="consent"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)} required/><label htmlFor="consent">Даю <a href="https://xn--m1ajn0a.xn--p1ai/docs/personal-data-consent.pdf" target="_blank" rel="noreferrer">согласие на обработку персональных данных</a> для ответа на заявку.</label></div>{status&&<p className="error" role="alert">{status}</p>}<button className="primary submit" disabled={busy} type="submit">{busy?'Отправляем заявку…':'Отправить заявку'}<ArrowRight size={20}/></button><p className="form-note">Расписание и стоимость сообщит администратор.<br/>Поля со звёздочкой обязательны.</p></form>}</div></section>
 <footer id="contacts"><div className="footer-top"><div><p className="eyebrow">ТАНЦЕВАЛЬНАЯ СТУДИЯ «ТЭНЦ»</p><h2>Увидимся <em>в студии.</em></h2></div><a className="footer-phone" href="tel:+79775553344">+7 977 555-33-44 <ArrowUpRight size={24}/></a></div><div className="footer-bottom"><p><MapPin size={17}/> Одинцово, Молодёжная улица, 46</p><a href="mailto:st.tenc@mail.ru">st.tenc@mail.ru</a><span>Балет · Современная хореография</span></div></footer></main></>;
}
